/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProductsCheckRouteImport } from './routes/products.check'
import { Route as ProductsEvidenceRouteImport } from './routes/products.evidence'
import { Route as ProductsRulesRouteImport } from './routes/products.rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCheckRoute = ProductsCheckRouteImport.update({
  id: '/products/check',
  path: '/products/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEvidenceRoute = ProductsEvidenceRouteImport.update({
  id: '/products/evidence',
  path: '/products/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRulesRoute = ProductsRulesRouteImport.update({
  id: '/products/rules',
  path: '/products/rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/products/check': typeof ProductsCheckRoute
  '/products/evidence': typeof ProductsEvidenceRoute
  '/products/rules': typeof ProductsRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/products/check': typeof ProductsCheckRoute
  '/products/evidence': typeof ProductsEvidenceRoute
  '/products/rules': typeof ProductsRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/products/check': typeof ProductsCheckRoute
  '/products/evidence': typeof ProductsEvidenceRoute
  '/products/rules': typeof ProductsRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/products/check'
    | '/products/evidence'
    | '/products/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/products/check'
    | '/products/evidence'
    | '/products/rules'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/products/check'
    | '/products/evidence'
    | '/products/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RequestDemoRoute: typeof RequestDemoRoute
  SigninRoute: typeof SigninRoute
  ProductsCheckRoute: typeof ProductsCheckRoute
  ProductsEvidenceRoute: typeof ProductsEvidenceRoute
  ProductsRulesRoute: typeof ProductsRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/check': {
      id: '/products/check'
      path: '/products/check'
      fullPath: '/products/check'
      preLoaderRoute: typeof ProductsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/evidence': {
      id: '/products/evidence'
      path: '/products/evidence'
      fullPath: '/products/evidence'
      preLoaderRoute: typeof ProductsEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rules': {
      id: '/products/rules'
      path: '/products/rules'
      fullPath: '/products/rules'
      preLoaderRoute: typeof ProductsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RequestDemoRoute: RequestDemoRoute,
  SigninRoute: SigninRoute,
  ProductsCheckRoute: ProductsCheckRoute,
  ProductsEvidenceRoute: ProductsEvidenceRoute,
  ProductsRulesRoute: ProductsRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
